### ISSUE TITLE
ImportError: cannot import name 'State' from 'sre_parse'

### ISSUE THREAD

**Issue by samanthaongyh** [PaddlePaddle/Quantum#35]
请问该怎么解决这个 error?
![image](https://user-images.githubusercontent.com/71283275/172329853-f5307646-766f-448a-b88c-37a495337f71.png)

**Comment by wangzihe1996** [comment]
你看看你的Python版本，我这里是Python3.8，是可以运行的。
以及我发现你的程序是旧版的程序，但是你运行的环境是新版的，因为2.2.0版本更新是不兼容更新，所以可能会有些问题。

其实图片里的这行报错的import是写的有问题的，这个后续会修复。

**Comment by skywalk163** [comment]
我这边试了下，确实python3.8是可以的，而AIStudio自带的python3.7，是不可以的。

请问在官方修复版本出来之前，有简单的代码修复解决方案吗？

**Comment by wangzihe1996** [comment]
其实只需要把container.py的21行的`from sre_parse import State`去掉即可。

**Comment by wangzihe1996** [comment]
This bug has been fixed by the version v2.2.1.

**Comment by DrTenma1998** [comment]
Update the exrex library: The issue may have been fixed in a newer version of exrex. Try updating the library with the following commands:

pip uninstall exrex 
pip install exrex
