### ISSUE TITLE
There are no kernels which are registered in the einsum operator.   [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] 

### ISSUE THREAD

**Issue by juhonkang** [PaddlePaddle/Quantum#36]
I have created a new env with conda python 3.8
Even colab cannot run yours :(
Could you provide notebooks on colab?

![image](https://user-images.githubusercontent.com/67153600/182743893-eca5104c-b934-4bea-b088-b797df46dad1.png)

**Comment by wangzihe1996** [comment]
这个是由paddle最新版本的一个bug导致的，经测试，paddle版本在2.2.0-2.3.0之间均可以。

**Comment by juhonkang** [comment]
So I should degrade it to 2.2.0-2.3.0, right?

**Comment by wangzihe1996** [comment]
> So I should degrade it to 2.2.0-2.3.0, right? pip install paddlepaddle==2.2?

Yes.
