### ISSUE TITLE
现在使用量子计算来训练模型，会有速度上的优势吗？

### ISSUE THREAD

**Issue by runvyang** [PaddlePaddle/Quantum#38]
还是说目前更多是尝试或者实验性质的

**Comment by wangzihe1996** [comment]
在模拟器上的话，主要是尝试和实验性质的；在量子计算机上，应该是可以有速度上的优势的。
PS: 讨论类的问题可以在Discussions板块发起。

**Comment by runvyang** [comment]
thanks, will do
