### ISSUE TITLE
Many of the examples dont work

### ISSUE THREAD

**Issue by BoltzmannEntropy** [PaddlePaddle/Quantum#42]
For instance:
QGAN_EN.iynb

```
RuntimeError: (NotFound) There are no kernels which are registered in the einsum operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < einsum > error]
```
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/91342039/212470271-039d0475-09b8-4f4d-a319-79c0c80ac1c7.png">

QAutoencoder_CN.ipynb:

`ValueError: (InvalidArgument) conj(): argument 'X' (position 0) must be Tensor, but got numpy.ndarray (at /paddle/paddle/fluid/pybind/op_function_common.cc:737)`

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/91342039/212470359-b25300c8-1431-462d-8982-92642eee26fe.png">

Can you help?

**Comment by CloudwinZL48** [comment]
Hello. I think you may need to check your Paddle Quantum version. All linear algbrea related functions, including the  ``dagger``  function, are compatible with ``numpy.ndarray``  since version ``2.2.2`` of the Paddle Quantum.

**Comment by BoltzmannEntropy** [comment]
I am on a machine without AVX, so this is what I had to do:

```
RUN python3.8 -m pip download paddlepaddle==2.3.2 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
RUN #python3.8 -m pip install paddlepaddle==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple paddle-quantum
RUN python3.8 -m pip install paddlepaddle-2.3.2-cp38-cp38-linux_x86_64.whl paddle-quantum
```

```
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle_quantum
>>> paddle_quantum.__version__
'2.2.0'


```
Any other option?

**Comment by CloudwinZL48** [comment]
Well I am nor familiar with AVX. But a possible temporary solution is to run the [old tutorials](https://github.com/PaddlePaddle/Quantum/tree/v2.2.0/tutorials) supported by the version 2.2.0 of Paddle Quantum.

But I still recommend you to upgrade Paddle Quantum to the newest version for better user experiences (if you can find other ways to solve the installation problem).

**Comment by BoltzmannEntropy** [comment]
Since paddle-quantum is dependent on paddle, and the latest paddle version for no-avx is 2.3.2, I can not install 2.2.2. 
I really want the newest version, but this is an Ubuntu based docker running inside OSX with the M1 chip. See here: 
https://github.com/BoltzmannEntropy/QMLDocker

**Comment by CloudwinZL48** [comment]
Is it possible to downgrade your PaddlePaddle version to 2.3.0 and then upgrade Paddle Quantum?

**Comment by BoltzmannEntropy** [comment]
Splendid, it works, thank you so much. I updated the docker file.
